sudo: required

dist: trusty

language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    env: COMPILER=g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - libgmp-dev
        - libmpfr-dev
        - libqd-dev
  - os: osx
    compiler: clang
    env: COMPILER=clang++
    before_install:
      - brew install gmp mpfr qd autoconf automake libtool 

install:
  - export CXX="$COMPILER"
  - $CXX --version

before_script:
  - "./autogen.sh"

script:
  - "./configure"
  - make
  - make check
  - make distcheck

notifications:
  on_success: change
  on_failure: always

deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: WsT8rFbwkPlsti2VTEsItUgkWyrhL68ybouz5/U0vGhI/KC3xh2CXhzlJes/vKaTli6GI+xLtwLz3gw7hruEGBnQ/bUCpKoljuF087fXjCGs93Vk7V5kPxfWEZ8p4YhuOVi2HVdp9zeiPOW+Nk2UMIjz19Bne2aypOIxcCfyI5c=
  file: fplll-*.tar.gz
  on:
    repo: fplll/fplll
    tags: true
    all_branches: true
