sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang
    - libmpfr-dev
    - libgmp-dev
    - libqd-dev

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  
before_script:
  - ./autogen.sh

script:
  - ./configure
  - make
  - make check
  - make dist

notifications:
  on_success: change
  on_failure: always
