sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgmp-dev
      - libmpfr-dev
      - libqd-dev
      - g++-4.9
      - g++-5
      
matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9
    - compiler: gcc
      env: COMPILER=g++-5
    - compiler: clang

install:
  export CXX="$COMPILER"

before_script:
  - ./autogen.sh

script:
  - ./configure
  - make
  - make check
  - make dist

notifications:
  on_success: change
  on_failure: always
